### ISSUE TITLE
wrong message when run plop 

### ISSUE THREAD

**Issue by JjpK** [plopjs/plop#337]
import { Plop, run } from "../src/plop.js";
       ^

SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

**Comment by JjpK** [comment]
is there something wrong in my running environment？

**Comment by crutchcorn** [comment]
Which version of Node, OS, and Plop are you using? 

And more specifically, what command are you running?

**Comment by SassNinja** [comment]
@JjpK I guess your node version is too old... at least I can reproduce your error when I switch to node v10 and try to execute plop

**Comment by crutchcorn** [comment]
Node 10 support was dropped in Plop 3. 

Closing the issue, since we have a seemingly solid answer for why this occurs. Please reopen if this issue is reproduced with Node 12+
