### ISSUE TITLE
Error [ERR_REQUIRE_ESM]

### ISSUE THREAD

**Issue by fjbalsamo** [plopjs/plop#355]
Hi, I'm trying to use node-plop with nestJS and have this problem.

```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: ~/node_modules/node-plop/src/index.js
require() of ES modules is not supported.
require() of ~/node_modules/node-plop/src/index.js from ~/template.service.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from ~/node_modules/node-plop/package.json.

    at new NodeError (internal/errors.js:322:7)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1102:13)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (~/template.service.ts:5:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32
```

**Comment by crutchcorn** [comment]
This seems to be an issue with the implementing side of things. You must use an ESM package to `import` `node-plop@0.30.0` and beyond. `require` is not allowed.

The error actually provides some means of how to fix this (namely, changing `"type": "module"` in your `package.json` and migrating your code to ESM

**Comment by William-Owen** [comment]
I am also getting Error `[ERR_REQUIRE_ESM]`. I have a repo with `"type": "module"` set in my `package.json`. I am using `"plop": "^3.1.1"` and my `plopfile.ts` is:

```Typescript
// plopfile.ts
import {NodePlopAPI} from "plop"

const plopProject = (plop: NodePlopAPI) => {

	const componentRoot = "./src/components"
	const templateRoot = "plop-templates"

	plop.setHelper("createFileName", (s) => s.replace(/[^a-z0-9]/gi, "_").toLowerCase())

	plop.setGenerator("Component", {
		description: "A new react component",
		prompts: [

			{
				type: "input",
				name: "componentName",
				message: "Component name",
			},

		],
		actions: [

			{
				type: "add",
				path: `${componentRoot}/{{componentName}}/{{componentName}}.tsx`,
				templateFile: `${templateRoot}/component/componentName.tsx.hbs`,
			},
			{
				type: "add",
				path: `${componentRoot}/{{componentName}}/{{componentName}}.module.sass`,
				templateFile: `${templateRoot}/component/componentName.sass.hbs`,
			},
			{
				type: "add",
				path: `${componentRoot}/{{componentName}}/index.tsx`,
				templateFile: `${templateRoot}/component/index.tsx.hbs`,
			},

		],

	})

}

export default plopProject

```
