### ISSUE TITLE
How can I bypass a prompt when I already have an answer?

### ISSUE THREAD

**Issue by AllanOricil** [plopjs/plop#450]
I tried  node-plop ` await generator.runPrompts(["projectName"])`, where

```js
prompts: [
      {
        type: "input",
        name: "projectName",
        message: "Project name?",
        default: "nrg-project",
      },
]
```

 but it did not work. I keep getting the following error

```bash
TypeError: String.prototype.split called on null or undefined
    at split (<anonymous>)
    at travel (file:///Users/allanoricil/nrg-cli/node_modules/inquirer/lib/ui/prompt.js:19:10)
    at Object.get (file:///Users/allanoricil/nrg-cli/node_modules/inquirer/lib/ui/prompt.js:26:20)
    at PromptUI.filterIfRunnable (file:///Users/allanoricil/nrg-cli/node_modules/inquirer/lib/ui/prompt.js:158:9)
    at doInnerSub (/Users/allanoricil/nrg-cli/node_modules/rxjs/dist/cjs/internal/operators/mergeInternals.js:22:31)
    at outerNext (/Users/allanoricil/nrg-cli/node_modules/rxjs/dist/cjs/internal/operators/mergeInternals.js:17:70)
    at OperatorSubscriber._this._next (/Users/allanoricil/nrg-cli/node_modules/rxjs/dist/cjs/internal/operators/OperatorSubscriber.js:33:21)
    at Subscriber.next (/Users/allanoricil/nrg-cli/node_modules/rxjs/dist/cjs/internal/Subscriber.js:51:18)
    at /Users/allanoricil/nrg-cli/node_modules/rxjs/dist/cjs/internal/operators/mergeInternals.js:28:28
    at OperatorSubscriber._this._next (/Users/allanoricil/nrg-cli/node_modules/rxjs/dist/cjs/internal/operators/OperatorSubscriber.js:33:21)
Waiting for the debugger to disconnect...
```

This debugger views show what happens after `await promptBypass`. Look at the values displayed in the debugger
<img width="1866" alt="image" src="https://github.com/user-attachments/assets/a60b33b0-c32c-4f58-8f72-c61b8c0d002d">

This debugger view show the internal execution of the `promptBypass`.
<img width="1869" alt="image" src="https://github.com/user-attachments/assets/f00f8201-67bf-4046-a3ee-8522381a1d13">

In your tests, after calling `promptBypass`, you verify the input values of each bypassed prompt, for example: 

```js
const [promptsAfterBypassTwo, bypassTwo] = await promptBypass(
      prompts,
      ["b", "something"],
      plop,
);
expect(bypassTwo.list).toBe("B");
expect(bypassTwo.input).toBe("something");
expect(promptsAfterBypassTwo.length).toBe(4);
```

However, in the run I shared above, it is clear that there is no "input" property in the bypassed prompt, inside `bypassAnswers`, which is equivalent to your `bypassTwo`. So, what is going wrong?

I'm using `plop@v4.0.1` and `node-plop@v0.32.0`

**Comment by AllanOricil** [comment]
relates to https://github.com/plopjs/plop/issues/445
